fNum = int(input("What is your first number?:"))
print(fNum)
sNum = int(input("What is your second number?:"))
add =(fNum+sNum)
sub =(fNum-sNum)
mult =(fNum*sNum)
divide = (fNum/sNum)
print(fNum,"+",sNum,"=",add)
print(fNum,"-",sNum,"=",sub)
print(fNum,"/",sNum,"=",mult)
print(fNum,"*",sNum,"=",divide)
